script: "bundle exec rake test"
cache: bundler
sudo: false
branches:
  only: master
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile
  - gemfiles/rails6.0.gemfile
matrix:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/rails3.2.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails6.0.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails6.0.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails6.0.gemfile
  allow_failures:
    - rvm: ruby-head
      gemfile: gemfiles/rails3.2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails4.2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails5.0.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails5.1.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails5.2.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails6.0.gemfile
