script: "bundle exec rake test"
cache: bundler
sudo: false
branches:
  only: master
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
