script: "bundle exec rake test"
cache: bundler
sudo: false
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.2
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
matrix:
  exclude:
    - rvm: 2.2.2
      gemfile: gemfiles/rails3.2.gemfile
