script: "bundle exec rake test"
rvm:
  - 1.9.3
  - 2.0
  - 2.1
gemfile:
  - gemfiles/activerecord_2.3.gemfile
  - gemfiles/activerecord_3.0.gemfile
  - gemfiles/activerecord_3.1.gemfile
  - gemfiles/activerecord_3.2.gemfile
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile
matrix:
  exclude:
    - rvm: 2.0
      gemfile: gemfiles/activerecord_2.3.gemfile
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/activerecord_2.3.gemfile
