name: ci
on: push
jobs:
  main:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
        gemfile:
          - rails6.1
          - rails7.0
          - rails7.1
        exclude:
          - ruby: '3.0'
            gemfile: rails6.1
          - ruby: '3.1'
            gemfile: rails6.1
        include:
          - {ruby: '2.7', gemfile: rails5.2}
          - {ruby: '2.7', gemfile: rails6.0}
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: zendesk/checkout@v2
      - uses: zendesk/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake test
