name: Publish public gem

on:
  push:
    branches: main
    paths: lib/**/version.rb

jobs:
  call-workflow:
    uses: zendesk/gw/.github/workflows/ruby-gem-publication.yml@main
    secrets:
      RUBY_GEMS_API_KEY: ${{ secrets.RUBY_GEMS_API_KEY }}
      RUBY_GEMS_TOTP_DEVICE: ${{ secrets.RUBY_GEMS_TOTP_DEVICE }}
